version: '2'

services:
    rsyncd:
        container_name: rsync-server
        build: .
        image: ekyna/rsync-server:latest
        environment:
            # REQUIRED: For user/password authentication
            - USERNAME=sftp
            - PASSWORD=password
            # OPTIONAL: Should be the same as the volume mapping of app container
            - VOLUME_PATH=/data
            # OPTIONAL: If you want to restrict access to the volume in read only mode. (default false)
            - READ_ONLY=false
            # OPTIONAL: If you want to chroot the use of rsync. Be sure that your directory structure is compatible.
            # See documentation
            # (default no)
            - CHROOT=no
            # OPTIONAL: restrict connection from (default: 0.0.0.0/0)
            - HOSTS_ALLOW=0.0.0.0/0
            # OPTIONAL: define the user name or user ID that file transfers to and from that module should take place
            # (default set to UID owner of VOLUME_PATH)
            - OWNER_ID = 1001
            # OPTIONAL: specifies one or more group names/IDs that will be used when accessing the module. The first one will be the default group, and any extra ones be set as supplemental groups.
            # (default set to GID owner of VOLUME_PATH)
            - GROUP_ID = 1001
        ports:
            - "7778:873"
            - "7777:22"
        volumes:
            - ./data:/data:rw
            # If config is mounted, it won't be generated from env vars.
            - ./rsyncd.conf:/etc/rsyncd.conf:ro